//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaOcaClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaOcaClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta nueva.
        /// </summary>
        public static string btnCrearCuenta {
            get {
                return ResourceManager.GetString("btnCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string btnEnviarCodigo {
            get {
                return ResourceManager.GetString("btnEnviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string btnGlobalEntrar {
            get {
                return ResourceManager.GetString("btnGlobalEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string btnGlobalRegresar {
            get {
                return ResourceManager.GetString("btnGlobalRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string btnGuardarCambios {
            get {
                return ResourceManager.GetString("btnGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string btnGuardarNuevaContraseña {
            get {
                return ResourceManager.GetString("btnGuardarNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string btnIniciarSesion {
            get {
                return ResourceManager.GetString("btnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        public static string btnOlvideMiContraseña {
            get {
                return ResourceManager.GetString("btnOlvideMiContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar código después de:.
        /// </summary>
        public static string btnReenviarCodigo {
            get {
                return ResourceManager.GetString("btnReenviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar.
        /// </summary>
        public static string btnVerificarCodigo {
            get {
                return ResourceManager.GetString("btnVerificarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor llena todos los campos.
        /// </summary>
        public static string camposVaciosLogin {
            get {
                return ResourceManager.GetString("camposVaciosLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario o contraseña contienen caracteres inválidos.
        /// </summary>
        public static string caracteresInvalidosLogin {
            get {
                return ResourceManager.GetString("caracteresInvalidosLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string contraseñaLogin {
            get {
                return ResourceManager.GetString("contraseñaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        public static string credencialesIncorrectasLogin {
            get {
                return ResourceManager.GetString("credencialesIncorrectasLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string globalAceptar {
            get {
                return ResourceManager.GetString("globalAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo obligatorio*.
        /// </summary>
        public static string globalCampoObligatorio {
            get {
                return ResourceManager.GetString("globalCampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string globalCancelar {
            get {
                return ResourceManager.GetString("globalCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteres inválidos*.
        /// </summary>
        public static string globalCaracteresInvalidos {
            get {
                return ResourceManager.GetString("globalCaracteresInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string globalConfiguración {
            get {
                return ResourceManager.GetString("globalConfiguración", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña:.
        /// </summary>
        public static string globalConfirmarContraseña {
            get {
                return ResourceManager.GetString("globalConfirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string globalContraseña {
            get {
                return ResourceManager.GetString("globalContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string globalContraseñasNoCoinciden {
            get {
                return ResourceManager.GetString("globalContraseñasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico:.
        /// </summary>
        public static string globalCorreo {
            get {
                return ResourceManager.GetString("globalCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string globalCrearCuenta {
            get {
                return ResourceManager.GetString("globalCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible conectarse a la base de datos. Por favor intente más tarde..
        /// </summary>
        public static string globalErrorBD {
            get {
                return ResourceManager.GetString("globalErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Por favor intente más tarde..
        /// </summary>
        public static string globalErrorServidor {
            get {
                return ResourceManager.GetString("globalErrorServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma preferente:.
        /// </summary>
        public static string globalIdiomaPreferente {
            get {
                return ResourceManager.GetString("globalIdiomaPreferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string globalJugarComoInvitado {
            get {
                return ResourceManager.GetString("globalJugarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string globalMsgBienvenido {
            get {
                return ResourceManager.GetString("globalMsgBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo:.
        /// </summary>
        public static string globalNombreCompleto {
            get {
                return ResourceManager.GetString("globalNombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario:.
        /// </summary>
        public static string globalNombreUsuario {
            get {
                return ResourceManager.GetString("globalNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privada.
        /// </summary>
        public static string globalPrivada {
            get {
                return ResourceManager.GetString("globalPrivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pública.
        /// </summary>
        public static string globalPublica {
            get {
                return ResourceManager.GetString("globalPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string globalRecuperarContraseña {
            get {
                return ResourceManager.GetString("globalRecuperarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string globalRegresar {
            get {
                return ResourceManager.GetString("globalRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string globalSala {
            get {
                return ResourceManager.GetString("globalSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string globalSalir {
            get {
                return ResourceManager.GetString("globalSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social.
        /// </summary>
        public static string globalSocial {
            get {
                return ResourceManager.GetString("globalSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibilidad.
        /// </summary>
        public static string globalVisibilidad {
            get {
                return ResourceManager.GetString("globalVisibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar la nueva contraseña:.
        /// </summary>
        public static string lbConfirmarNuevaContraseña {
            get {
                return ResourceManager.GetString("lbConfirmarNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar solicitud de amistad.
        /// </summary>
        public static string lbEnviarSolicitudAmistad {
            get {
                return ResourceManager.GetString("lbEnviarSolicitudAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código de verificación:.
        /// </summary>
        public static string lbIngresarCodigo {
            get {
                return ResourceManager.GetString("lbIngresarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su correo electrónico registrado:.
        /// </summary>
        public static string lbIngresarCorreo {
            get {
                return ResourceManager.GetString("lbIngresarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el nombre del jugador:.
        /// </summary>
        public static string lbIngresarNombreJugador {
            get {
                return ResourceManager.GetString("lbIngresarNombreJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la nueva contraseña:.
        /// </summary>
        public static string lbIngresarNuevaContraseña {
            get {
                return ResourceManager.GetString("lbIngresarNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        public static string lbInicioSesion {
            get {
                return ResourceManager.GetString("lbInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar cuenta.
        /// </summary>
        public static string lbModificarCuenta {
            get {
                return ResourceManager.GetString("lbModificarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu nombre de usuario temporal es:.
        /// </summary>
        public static string lbNombreUsuarioTemporal {
            get {
                return ResourceManager.GetString("lbNombreUsuarioTemporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tiene una cuenta?.
        /// </summary>
        public static string lbNoTengoCuenta {
            get {
                return ResourceManager.GetString("lbNoTengoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar imagen de perfil.
        /// </summary>
        public static string lbSeleccionarImagenPerfil {
            get {
                return ResourceManager.GetString("lbSeleccionarImagenPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas cancelar la creación de la cuenta?.
        /// </summary>
        public static string msgCancelarCreacionCuenta {
            get {
                return ResourceManager.GetString("msgCancelarCreacionCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta se ha creado correctamente..
        /// </summary>
        public static string msgCuentaCreada {
            get {
                return ResourceManager.GetString("msgCuentaCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado un código a su correo para restablecer la contraseña..
        /// </summary>
        public static string msgMensajeEnviado {
            get {
                return ResourceManager.GetString("msgMensajeEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amistad enviada..
        /// </summary>
        public static string msgSolicitudAmistadEnviada {
            get {
                return ResourceManager.GetString("msgSolicitudAmistadEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oca Aesthetic.
        /// </summary>
        public static string skinOcaAesthetic {
            get {
                return ResourceManager.GetString("skinOcaAesthetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oca Dibujada.
        /// </summary>
        public static string skinOcaDibujada {
            get {
                return ResourceManager.GetString("skinOcaDibujada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oca Fea.
        /// </summary>
        public static string skinOcaFea {
            get {
                return ResourceManager.GetString("skinOcaFea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oca Madre.
        /// </summary>
        public static string skinOcaMadre {
            get {
                return ResourceManager.GetString("skinOcaMadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oca Realista.
        /// </summary>
        public static string skinOcaRealista {
            get {
                return ResourceManager.GetString("skinOcaRealista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oca Triste.
        /// </summary>
        public static string skinOcaTriste {
            get {
                return ResourceManager.GetString("skinOcaTriste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string usuarioLogin {
            get {
                return ResourceManager.GetString("usuarioLogin", resourceCulture);
            }
        }
    }
}
